Added initial backend part for user registration
Lv-219-Python/MoniNag pull request #10
Opened 2017-01-22 20:04 UTC by orestch

2017-01-24 14:05 UTC, HenrikhB commented on moninag/moninag/settings.py
> +print (DATABASES)
unnecessary print

2017-01-24 14:36 UTC, mhumetskyi commented on moninag/registration/forms.py
> +from django.core.mail import EmailMultiAlternatives
Reoder imports
```
from django.core.mail import EmailMultiAlternatives
from django.contrib.auth.forms import UserCreationForm
from django.template.loader import render_to_string

from registration.models import CustomUser 
```

2017-01-24 14:56 UTC, mhumetskyi commented on moninag/registration/forms.py
> +        #import pdb; pdb.set_trace()
Unnecessary comment

2017-01-24 21:35 UTC, lisovyk approved these changes

2017-01-25 15:16 UTC, hutsulyk requested changes
Add email settings in **README.md** which are necessary in **local_settings.py**

- Email settings

```
  ACCOUNT_ACTIVATION_DAYS = 7
  EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
  EMAIL_PORT = 587
  EMAIL_HOST_USER = 'moninaginfo@gmail.com'
  EMAIL_HOST_PASSWORD = '1234rewqasdfvcxz'
  EMAIL_USE_TLS = True
  EMAIL_HOST = 'smtp.gmail.com'
  DEFAULT_FROM_EMAIL = 'moninaginfo@gmail.com'
  WSGI_APPLICATION = 'moninag.wsgi.application'
  ```

2017-01-25 15:16 UTC, hutsulyk commented on moninag/registration/models.py
> +    email       = models.EmailField(blank=True, unique=True)
Email should be **required field**, otherwise user could sign up  without entering email.
Make it `blank=False`

2017-01-25 15:53 UTC, mhumetskyi commented on moninag/registration/views.py
> +from moninag.settings import DEFAULT_FROM_EMAIL, DEFAULT_HOST
Change `DEFAULT_HOST` to `EMAIL_HOST`

2017-01-25 15:53 UTC, mhumetskyi commented on moninag/registration/views.py
> +            send_activation_email(DEFAULT_HOST, DEFAULT_FROM_EMAIL, email, user_id)
Change `DEFAULT_HOST` to `EMAIL_HOST`

2017-01-26 07:51 UTC, HenrikhB commented on moninag/registration/admin.py
> +# Register your models here.
delete default comment

2017-01-26 07:57 UTC, HenrikhB commented on moninag/registration/models.py
> +    avatar       =  models.CharField(default='', max_length=1000, editable=False)
this probably doesn't fit PEP8 (multiple spaces before operator)

2017-01-28 11:40 UTC, mhumetskyi commented on moninag/moninag/settings.py
> +        'PORT': ''
Empty  default database settings

2017-01-28 11:54 UTC, mhumetskyi commented on moninag/templates/registration/register.html
> +{% endblock %}
Add end line

2017-01-28 12:10 UTC, hutsulyk approved these changes

2017-01-28 12:10 UTC, HenrikhB commented on moninag/registration/models.py
> +    avatar =  models.CharField(default='', max_length=1000, editable=False)
multiple spaces after operator

2017-01-28 12:14 UTC, HenrikhB commented on moninag/registration/views.py
> +def login(request):
expected 2 blank lines, found 1

2017-01-28 12:25 UTC, hutsulyk reviewed
User sign up, activation, sign in, gravatar integration, work good, and all migrations applied without conflicts! :+1:

2017-01-29 00:11 UTC, HenrikhB commented on moninag/registration/models.py
> +    avatar =  models.CharField(default='', max_length=1000, editable=False)
multiple spaces after operator!

2017-01-29 00:27 UTC, ghost requested changes
moninag/registration/views.py doesn't fit PEP8 - reformat code (~10 issues)

2017-01-29 00:27 UTC, HenrikhB commented on moninag/registration/views.py
> +
expected 2 blank lines, found 1

2017-01-29 00:27 UTC, HenrikhB commented on moninag/registration/views.py
> +def login(request):
expected 2 blank lines, found 1

2017-01-29 00:27 UTC, HenrikhB commented on moninag/registration/views.py
> +def auth_view(request):
expected 2 blank lines, found 1

2017-01-29 00:27 UTC, HenrikhB commented on moninag/registration/views.py
> +    user = CustomUser.objects.get(id = activation_key)
unexpected spaces around keyword / parameter equals

2017-01-29 09:08 UTC, ghost approved these changes

2017-01-29 09:12 UTC, merged