nagios-plugins install
Lv-219-Python/MoniNag pull request #12
Opened 2017-01-25 16:45 UTC by s0812

2017-01-26 13:26 UTC, byshovets requested changes
Use package manager, Luke.
\# sudo apt-get install nagios-plugins

2017-02-01 23:10 UTC, mhumetskyi commented
Installed successfully. Resolve conflicts to merge.

2017-02-03 11:31 UTC, hutsulyk approved these changes

2017-02-07 12:03 UTC, byshovets approved these changes

2017-02-07 12:05 UTC, merged