Created Check View
Lv-219-Python/MoniNag pull request #19
Opened 2017-02-03 06:57 UTC by s0812

2017-02-03 11:36 UTC, mhumetskyi commented on moninag/check/models.py
> +        return cls.objects.all()[start:end]
`id` argument never used.

2017-02-03 11:39 UTC, mhumetskyi commented on moninag/check/views.py
> +            return JsonResponse(json_response, status=201)
Create twice the same object `Check.create(**check_dict)`

2017-02-03 11:41 UTC, mhumetskyi commented on moninag/moninag/settings.py
> -    'django.middleware.csrf.CsrfViewMiddleware',
Check if sign in, sign up still work without `CsrfViewMiddleware`

2017-02-03 12:52 UTC, s0812 commented on moninag/check/models.py
> +        return cls.objects.all()[start:end]
id argument was deleted

2017-02-03 12:56 UTC, s0812 commented on moninag/check/views.py
> +            return JsonResponse(json_response, status=201)
Using var `check` instead of.

2017-02-03 12:57 UTC, s0812 commented on moninag/moninag/settings.py
> -    'django.middleware.csrf.CsrfViewMiddleware',
Added back.

2017-02-03 13:11 UTC, mhumetskyi commented on moninag/moninag/urls.py
> +    url(r'^api_01/check/', include('check.urls')),
Replace on `url(r'^api/1/check/', include('check.urls')),`
I have changed too for Service View.
Liubomyr suggested :slightly_smiling_face:

2017-02-03 13:31 UTC, s0812 commented on moninag/moninag/urls.py
> +    url(r'^api_01/check/', include('check.urls')),
Done

2017-02-03 13:56 UTC, mhumetskyi commented
Update with dev :slightly_smiling_face:

2017-02-03 14:11 UTC, mhumetskyi commented on moninag/check/models.py
> +            service = Service.objects.get(id=service_id)
Use `Service.get_by_id` insted.

2017-02-03 14:12 UTC, mhumetskyi commented on moninag/check/models.py
> +            service = Service.objects.get(id=service_id)
Use `Service.get_by_id` insted.

2017-02-03 14:13 UTC, mhumetskyi commented on moninag/check/views.py
> +    return not bool(REQUIREMENTS ^ set(dictionary.keys()))
Use `validate_dict` from utils :slightly_smiling_face:

2017-02-03 16:22 UTC, s0812 commented on moninag/check/views.py
> +    return not bool(REQUIREMENTS ^ set(dictionary.keys()))
`validate_dict` imported from `utils`

2017-02-03 16:46 UTC, s0812 commented on moninag/check/models.py
> +            service = Service.objects.get(id=service_id)
`get_by_id` is not a method of `Service` class

2017-02-03 16:54 UTC, s0812 commented on moninag/check/models.py
> +            service = Service.objects.get(id=service_id)
sry, my fault. Didnt pull my local repo.

2017-02-03 20:07 UTC, ghost approved these changes

2017-02-03 20:56 UTC, mhumetskyi commented on moninag/moninag/urls.py
> +    url(r'^', include('home.urls')),w
What for `w`? :upside_down_face:

2017-02-03 20:59 UTC, mhumetskyi commented on moninag/utils/validate.py
> +    return not bool(requirements ^ set(dictionary.keys()))
Duplicated code. Use validator.py

2017-02-04 09:56 UTC, s0812 commented on moninag/check/models.py
> +            service = Service.objects.get(id=service_id)
`Service.get_by_id` is working now.

2017-02-04 09:57 UTC, s0812 commented on moninag/check/models.py
> +            service = Service.objects.get(id=service_id)
Replaced `Service.objects.get` via `Service.get_by_id`.

2017-02-04 09:57 UTC, s0812 commented on moninag/moninag/urls.py
> +    url(r'^', include('home.urls')),w
Deleted 'w' symbol.

2017-02-04 09:58 UTC, s0812 commented on moninag/utils/validate.py
> +    return not bool(requirements ^ set(dictionary.keys()))
Renamed `validate.py` into `validator.py`.

2017-02-05 15:33 UTC, hutsulyk requested changes
You shouldn't rename `validators.py` to `validator.py`, because other modules use it with name `validators`.
After rename they will not work. And they are not, try to runsever :upside_down_face: 

From the very beginning you had to use `validate_dict` function from already written `validators.py`.
There was no need to create your own file or modify existing.

2017-02-05 16:10 UTC, hutsulyk commented
`urls.py` is missing for check.

2017-02-05 16:57 UTC, mhumetskyi commented on moninag/check/models.py
> +            return None
`Service.get_by_id(id=service_id)` return None, if service wasn't found.

2017-02-05 16:59 UTC, mhumetskyi commented on moninag/check/models.py
> +            return None
`Service.get_by_id(id=service_id)` return None without exception, if service wasn't found.

2017-02-05 19:01 UTC, hutsulyk approved these changes

2017-02-06 10:16 UTC, lhalam reviewed
make changes to files based on the comments

2017-02-06 10:16 UTC, lhalam commented on moninag/check/models.py
> +    @classmethod
use @staticmetod

2017-02-06 10:16 UTC, lhalam commented on moninag/check/models.py
> +        service = Service.get_by_id(id=service_id)
Remove this line? because the method receives the existing service_id

2017-02-06 10:16 UTC, lhalam commented on moninag/check/models.py
> +    @classmethod
remove @classmethod
it is instance method

2017-02-07 14:52 UTC, mhumetskyi commented on moninag/check/models.py
> +        check.service = Service.get_by_id(service_id)
Except service instance as parameters instead of `service_id`

2017-02-07 14:53 UTC, mhumetskyi commented on moninag/check/models.py
> +        return self
Is it necessary to return self?

2017-02-07 15:07 UTC, mhumetskyi commented
Add user verification to view :slightly_smiling_face:

2017-02-07 16:02 UTC, ghost requested changes

2017-02-07 16:02 UTC, HenrikhB commented on moninag/check/views.py
> +        checks = Check.get()
'Check' has no method 'get'

2017-02-09 16:26 UTC, mhumetskyi commented on moninag/moninag/urls.py
>  ]
Did you accidentally delete server api url? :slightly_smiling_face: 
`url(r'^api/1/server/', include('server.urls')),`

2017-02-09 16:46 UTC, s0812 commented on moninag/moninag/urls.py
>  ]
Emmm, sry)

2017-02-09 17:04 UTC, mhumetskyi commented on moninag/moninag/urls.py
>  ]
The root of problem is that your branch is not up-to-date with dev.

Rebase or merge with dev :upside_down_face:

2017-02-09 17:06 UTC, mhumetskyi commented
> This branch has conflicts that must be resolved

Update with dev :slightly_smiling_face:

2017-02-10 15:24 UTC, mhumetskyi commented
Update with dev again (`git rebase dev`) :slightly_smiling_face:

2017-02-10 15:53 UTC, lhalam commented on moninag/check/views.py
> +            if count:
remove this check, it is not necessary

2017-02-10 16:26 UTC, s0812 commented on moninag/check/views.py
> +            if count:
@lhalam removed check

2017-02-10 18:24 UTC, hutsulyk approved these changes

2017-02-10 21:27 UTC, lhalam approved these changes

2017-02-11 01:05 UTC, ghost approved these changes

2017-02-11 08:50 UTC, merged