plugin testing
Lv-219-Python/MoniNag pull request #29
Opened 2017-02-16 16:47 UTC by maaraanas

nagiosplugin tests

2017-02-16 17:22 UTC, mhumetskyi commented on moninag/tests/unittests/plugin/test_model.py
> +        # )
Delete unused code :slightly_smiling_face:

2017-02-16 17:23 UTC, ghost requested changes

2017-02-16 17:23 UTC, HenrikhB commented on moninag/tests/unittests/plugin/test_model.py
> +        print(result)
remove print

2017-02-16 17:23 UTC, HenrikhB commented on moninag/tests/unittests/plugin/test_model.py
> +        # )
make a proper setup

2017-02-16 17:23 UTC, HenrikhB commented on moninag/tests/unittests/plugin/test_view.py
> +from nagplugin.models import NagPlugin
format import according to PEP8

2017-02-16 17:23 UTC, HenrikhB commented on moninag/tests/unittests/plugin/test_view.py
> +        self.user = authenticate(username='test@test.com', password='password')
you can remove  this line

2017-02-16 17:23 UTC, HenrikhB commented on moninag/tests/unittests/plugin/test_view.py
> +        """Ensure that GET method returns specific server for authenticated user and 200 status"""
server => plugin

2017-02-16 17:23 UTC, HenrikhB commented on moninag/tests/unittests/plugin/test_view.py
> +        # Create expected specific server response
server => plugin

2017-02-16 17:23 UTC, HenrikhB commented on moninag/tests/unittests/plugin/test_model.py
> +    def test_get_by_id(self):
too many blank lines (2)

2017-02-16 17:23 UTC, HenrikhB commented on moninag/tests/unittests/plugin/test_model.py
> +        self.assertQuerysetEqual(result, map(repr,expected), ordered=False)
missing whitespace after ','

2017-02-16 17:23 UTC, HenrikhB commented on moninag/tests/unittests/plugin/test_model.py
> +    def test_get_by_name(self):
expected 1 blank line, found 0

2017-02-16 17:23 UTC, HenrikhB commented on moninag/tests/unittests/plugin/test_model.py
> +    def test_to_dict(self):
missing whitespace after ','

2017-02-16 17:23 UTC, mhumetskyi commented on moninag/tests/unittests/plugin/test_model.py
> +        print(result)
Remove print

2017-02-16 17:26 UTC, ghost requested changes

2017-02-16 17:26 UTC, HenrikhB commented on moninag/tests/unittests/plugin/test_model.py
> +                                                                                            plugin.name,
line too long (104 > 79 characters)

2017-02-16 17:26 UTC, HenrikhB commented on moninag/tests/unittests/plugin/test_model.py
> +                                                                                            plugin.name,
continuation line over-indented for visual indent

2017-02-16 17:26 UTC, HenrikhB commented on moninag/tests/unittests/plugin/test_model.py
> +                                                                                            )
closing bracket does not match visual indentation

2017-02-16 17:26 UTC, HenrikhB commented on moninag/tests/unittests/plugin/test_view.py
> +def to_dict(plugin):
expected 2 blank lines, found 1

2017-02-16 17:26 UTC, HenrikhB commented on moninag/tests/unittests/plugin/test_view.py
> +class TestNagPluginView(TestCase):
expected 2 blank lines, found 0

2017-02-16 17:26 UTC, HenrikhB commented on moninag/tests/unittests/plugin/test_view.py
> +    def test_get_plugin(self):
expected 2 blank lines, found 0

2017-02-16 17:48 UTC, ghost requested changes

2017-02-16 17:48 UTC, HenrikhB commented on moninag/tests/unittests/plugin/test_model.py
> +        """Ensure that get_by_name returns all servers for specific name"""
servers => plugins

2017-02-16 17:48 UTC, HenrikhB commented on moninag/tests/unittests/plugin/test_model.py
> +from nagplugin.models import NagPlugin
reorder according to pep8

2017-02-17 00:35 UTC, ghost approved these changes

2017-02-17 11:15 UTC, hutsulyk requested changes
Name folder in unittests same as application name.
Rename folder `plugin` into `nagplugin`.

2017-02-17 11:19 UTC, mhumetskyi commented on moninag/tests/unittests/plugin/test_model.py
> +class TestPlugin(TestCase):
Expected 2 blank line before class :slightly_smiling_face:

2017-02-17 11:23 UTC, mhumetskyi commented on moninag/tests/unittests/plugin/test_view.py
> +from django.contrib.auth import authenticate
Unused import :slightly_smiling_face:

2017-02-17 11:25 UTC, mhumetskyi commented on moninag/tests/unittests/plugin/test_view.py
> +class TestNagPluginView(TestCase):
Expected 2 blank line before class :upside_down_face:

2017-02-17 11:41 UTC, mhumetskyi commented on moninag/tests/unittests/plugin/test_view.py
> +        plugins = NagPlugin.get(None)
Unnecessary paramater `None` :upside_down_face:

2017-02-20 00:44 UTC, mhumetskyi commented on moninag/tests/unittests/nagplugin/test_model.py
> +        self.assertEqual(result, None)
Use `assertIsNone` :slightly_smiling_face:

2017-02-20 00:45 UTC, mhumetskyi commented on moninag/tests/unittests/nagplugin/test_model.py
> +        """Ensure that get method returns specific plugin using id"""
You don't use id :upside_down_face:

2017-02-20 00:49 UTC, mhumetskyi commented on moninag/tests/unittests/nagplugin/test_view.py
> +        self.assertJSONEqual(response.content.decode('utf-8'), expected_json_response)
You are comparing `str` with `dict`. 
I am not sure, but maybe it is better to convert dict to JSON string, to compare same types.
Ask @lhalam to be sure :slightly_smiling_face:

2017-02-20 00:51 UTC, mhumetskyi commented on moninag/tests/unittests/nagplugin/test_view.py
> +import json
Unused import :upside_down_face: 
(but maybe it will be necessary, look next comment) :next_track_button:

2017-02-24 12:28 UTC, maaraanas commented on moninag/tests/unittests/nagplugin/test_view.py
> +import json
now used ;)

2017-02-24 14:30 UTC, hutsulyk reviewed
Fix one comment, everything else is fine! :slightly_smiling_face: 

Make rebase with dev, to keep right history :loop:

2017-02-24 14:30 UTC, mhumetskyi commented on moninag/tests/unittests/nagplugin/test_view.py
> +    }
Unused method

2017-02-28 10:26 UTC, maaraanas commented on moninag/tests/unittests/nagplugin/test_view.py
> +    }
wer useing it to get expected json

2017-02-28 12:08 UTC, hutsulyk approved these changes
Nice work :slightly_smiling_face:

2017-02-28 12:17 UTC, merged