30 service unit testing
Lv-219-Python/MoniNag pull request #31
Opened 2017-02-19 21:04 UTC by zirka28

2017-02-19 21:30 UTC, ghost requested changes

2017-02-19 21:30 UTC, HenrikhB commented on moninag/tests/servise_model_test.py
> +class ServiceTest(TestCase):
expected 2 blank lines, found 1

2017-02-19 21:30 UTC, HenrikhB commented on moninag/tests/servise_model_test.py
> +        user=CustomUser.objects.create(id=1, first_name="firstname", second_name="secondname", email="email@gmail.com")
missing whitespace around operator

2017-02-19 21:30 UTC, HenrikhB commented on moninag/tests/servise_model_test.py
> +        user=CustomUser.objects.create(id=1, first_name="firstname", second_name="secondname", email="email@gmail.com")
line too long (119 > 79 characters)

2017-02-19 21:30 UTC, HenrikhB commented on moninag/tests/servise_model_test.py
> +        server=Server.objects.create(id =1, name="name", address="address", state="Production", user=user)
unexpected spaces around keyword / parameter equals

2017-02-19 21:30 UTC, HenrikhB commented on moninag/tests/servise_model_test.py
> +        self.assertEqual(service.status,"ok")
missing whitespace after ','

2017-02-19 21:30 UTC, HenrikhB commented on moninag/tests/servise_model_test.py
> +    def test_service_get_by_id(self):
too many blank lines (2)

2017-02-19 21:30 UTC, HenrikhB commented on moninag/tests/unittests/service/test_service_model.py
> +from service.models import Service
blank line between project and third party imports

2017-02-19 21:30 UTC, HenrikhB commented on moninag/tests/unittests/service/test_service_model.py
> +class ServiceTest(TestCase):
expected 2 blank lines, found 1

2017-02-19 21:30 UTC, HenrikhB commented on moninag/tests/unittests/service/test_service_model.py
> +        user=CustomUser.objects.create(id=1, first_name="firstname", second_name="secondname", email="email@gmail.com")
missing whitespace around operator

2017-02-19 21:30 UTC, HenrikhB commented on moninag/tests/unittests/service/test_service_model.py
> +        user=CustomUser.objects.create(id=1, first_name="firstname", second_name="secondname", email="email@gmail.com")
line too long (119 > 100 characters)

2017-02-19 21:30 UTC, HenrikhB commented on moninag/tests/unittests/service/test_service_model.py
> +        server=Server.objects.create(id =1, name="name", address="address", state="Production", user=user)
unexpected spaces around keyword / parameter equals

2017-02-19 21:30 UTC, HenrikhB commented on moninag/tests/unittests/service/test_service_model.py
> +        self.assertEqual(service.server, server)
missing whitespace after ','

2017-02-19 21:30 UTC, HenrikhB commented on moninag/tests/unittests/service/test_service_view.py
> +                           'user_id':18 })
whitespace before '}'

2017-02-19 21:30 UTC, HenrikhB commented on moninag/tests/unittests/service/test_service_view.py
> +        self.user = authenticate(username='email@gmail.com', password='qwerty')
actually you dont need this line 😄

2017-02-19 21:30 UTC, HenrikhB commented on moninag/tests/unittests/service/test_service_view.py
> +    def test_put_not_user_service(self):
expected 1 blank line, found 0

2017-02-19 21:33 UTC, HenrikhB commented on moninag/tests/unittests/service/test_service_view.py
> +import json
reorder imports according to pep8

2017-02-20 01:08 UTC, HenrikhB commented on moninag/tests/unittests/service/test_service_model.py
> +                               status="ok", server=server2)
newline before server=server2

2017-02-20 01:09 UTC, HenrikhB commented on moninag/tests/unittests/service/test_service_model.py
> +        server = Server.objects.create(id=1,
unused variable server, probably you don't need this assignment

2017-02-20 01:10 UTC, HenrikhB commented on moninag/tests/unittests/service/test_service_model.py
> +        user1 = CustomUser.objects.create(id=2,
unused variable **user1**, probably you don't need this assignment

2017-02-20 01:27 UTC, mhumetskyi commented on moninag/tests/unittests/service/test_service_model.py
> +        actual = Service.objects.filter(server__in=servers)
You could simplify this :slightly_smiling_face: 
`services = Service.objects.filter(server__user__id=3)`

2017-02-20 01:30 UTC, mhumetskyi commented on moninag/tests/unittests/service/test_service_view.py
> +                             expected_response)
Comparing `str` to `dict` :upside_down_face:

2017-02-20 01:32 UTC, mhumetskyi commented on moninag/tests/unittests/service/test_service_view.py
> +        self.assertEqual(service.server.id, 10)
It is better to check `actual_response` JSON :slightly_smiling_face:

2017-02-20 01:33 UTC, mhumetskyi commented on moninag/tests/unittests/service/test_service_view.py
> +        self.assertEqual(service.status, 'fail')
It is better to check `actual_response` JSON :upside_down_face:

2017-02-20 09:17 UTC, zirka28 commented on moninag/tests/unittests/service/test_service_model.py
> +        server = Server.objects.create(id=1,
Now I use it :)

2017-02-22 17:39 UTC, mhumetskyi commented
`__init__.py` is missing :upside_down_face: 

Everything else works and looks good!

2017-02-22 19:03 UTC, ghost requested changes
I guess you should add docstrings for each test function since tests in dev already have them and it will help to avoid additional work when we will integrate with Jenkins

2017-02-23 23:11 UTC, hutsulyk approved these changes

2017-02-24 11:29 UTC, ghost approved these changes

2017-02-25 05:35 UTC, merged