28 auth unit testing
Lv-219-Python/MoniNag pull request #36
Opened 2017-02-27 13:05 UTC by lisovyk

Rewrote tests for registration/model

2017-02-27 22:40 UTC, lhalam requested changes

2017-02-27 22:40 UTC, lhalam commented on moninag/tests/unittests/registration/test_model.py
> +        self.assertEqual(user.get_by_id(44444), None)
use assertIsNone()

```
user = CustomUser.get_by_id(44444)
self.assertIsNone(user)
```

2017-02-27 22:40 UTC, lhalam commented on moninag/tests/unittests/registration/test_model.py
> +        user = CustomUser()
```
user = CustomUser()
user = user.get_by_id(2)
```
to
```
user = CustomUser.get_by_id(2)
```

2017-02-28 02:19 UTC, mhumetskyi commented
Rebase with dev :slightly_smiling_face:

2017-02-28 16:48 UTC, mhumetskyi commented on moninag/tests/unittests/registration/test_model.py
> +        self.assertEqual(user.get_full_name(), "TestName TestSecondName")
Test failed
```AttributeError: 'CustomUser' object has no attribute 'last_name'```

2017-02-28 18:57 UTC, lhalam commented on moninag/tests/unittests/registration/test_model.py
> +        user.save()
```
user.save()
expected = Server.objects.get(id=user.id)
self.assertEqual(user, expected)
```

2017-02-28 18:57 UTC, lhalam commented on moninag/tests/unittests/registration/test_model.py
> +        self.assertEqual(user.first_name, "UpdatedName")
```
expected_user =  CustomUser.objects.get(email="test@test.test")
self.assertEqual(expected_user .first_name, "UpdatedName")
```

2017-02-28 19:05 UTC, ghost requested changes

2017-02-28 19:05 UTC, HenrikhB commented on moninag/tests/unittests/registration/test_model.py
> +from registration.models import CustomUser
proper import format (separate 3rd party imports from our project imports)

2017-02-28 19:05 UTC, HenrikhB commented on moninag/tests/unittests/registration/test_model.py
> +        self.assertEqual(user.id, 2)
i would suggest to compare entire users, not only the id. (CustomUser.objects.get(id=id and CustomUser.get_by_id(2))

2017-03-01 10:10 UTC, lisovyk commented on moninag/tests/unittests/registration/test_model.py
> +        self.assertEqual(user.get_full_name(), "TestName TestSecondName")
There is a wrong attribute in model. I will change that with the next commit.

2017-03-01 15:34 UTC, lhalam approved these changes

2017-03-02 00:17 UTC, hutsulyk approved these changes

2017-03-02 07:51 UTC, ghost approved these changes
seems to be OK

2017-03-02 10:04 UTC, merged