46 implement header
Lv-219-Python/MoniNag pull request #37
Opened 2017-02-28 01:41 UTC by mhumetskyi

2017-02-28 09:44 UTC, lisovyk requested changes
Add minor changes, endlines.

2017-02-28 09:44 UTC, lisovyk commented on moninag/package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
Shouldn't it be 4 spaces tabulation here?

2017-02-28 09:44 UTC, lisovyk commented on moninag/static/src/ts/app/app-header/app-header.component.html
> +</div>
Add endline

2017-02-28 09:44 UTC, lisovyk commented on moninag/static/src/ts/app/app-header/app-header.component.ts
> +}
Endline.

2017-02-28 09:44 UTC, lisovyk commented on moninag/static/src/ts/app/user-profile/user-profile.component.html
>  </div>
Endline

2017-02-28 09:58 UTC, mhumetskyi commented on moninag/package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
When we save some package with `npm i --save` it reformat file with 2 spaces indents.
So let it be with 2 spaces indents. :slightly_smiling_face:

2017-02-28 09:59 UTC, mhumetskyi commented on moninag/static/src/ts/app/app-header/app-header.component.html
> +</div>
It present :eyes:

2017-02-28 10:00 UTC, mhumetskyi commented on moninag/static/src/ts/app/app-header/app-header.component.ts
> +}
It is here too :eyes:

2017-02-28 10:00 UTC, mhumetskyi commented on moninag/static/src/ts/app/user-profile/user-profile.component.html
>  </div>
It present again :upside_down_face:

2017-02-28 10:00 UTC, lisovyk commented on moninag/static/src/ts/app/app-header/app-header.component.html
> +</div>
Now I get it. It shows it as a "+" line. Everything's perfect then :eyes:

2017-02-28 10:01 UTC, lisovyk approved these changes

2017-02-28 17:11 UTC, maaraanas commented on moninag/static/src/ts/app/app-header/app-header.component.html
> +</div>
Why md-menu, and not a md-tab?

2017-02-28 17:13 UTC, maaraanas commented on moninag/static/src/ts/app/user-profile/user-profile.component.html
>  </div>
what do u think, about useing md-card here?

2017-02-28 18:34 UTC, ghost approved these changes

2017-02-28 18:34 UTC, HenrikhB commented on moninag/package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
we can use  jsonlint to have a proper format with 4 spaces 
`npm install --save-dev jsonlint` or smth like that, but it doesn't really matter.

2017-02-28 19:20 UTC, mhumetskyi commented on moninag/static/src/ts/app/app-header/app-header.component.html
> +</div>
Because it is like small pop up menu, and no different content to display like tabs :slightly_smiling_face: 
It is done like in Trello :eyes:

2017-02-28 19:25 UTC, mhumetskyi commented on moninag/static/src/ts/app/user-profile/user-profile.component.html
>  </div>
Good idea, but I will do it in separate task, for now I just remove bootstrap styles and add flex layout, so it looks readable :upside_down_face:

2017-02-28 20:11 UTC, lhalam commented on moninag/static/src/ts/app/app-header/app-header.component.ts
> +            error => console.log(error));
repository should not be console.log ()
you ought to have error handler

2017-03-01 13:29 UTC, lhalam approved these changes

2017-03-01 13:30 UTC, merged