7 service model
Lv-219-Python/MoniNag pull request #4
Opened 2017-01-18 12:09 UTC by mhumetskyi

Task "Service model"

2017-01-18 12:30 UTC, lhalam commented on moninag/service/admin.py
> +# Register your models here.
delete this comment

2017-01-18 12:30 UTC, lhalam commented on moninag/service/tests.py
> +# Create your tests here.
delete this comment

2017-01-18 12:30 UTC, lhalam commented on moninag/service/views.py
> +# Create your views here.
delete this comment

2017-01-18 17:30 UTC, byshovets requested changes
I would like to see readable commit-history like:
* Created Service model
* Add deployment steps for Ubuntu
* Add Sublime and PyCharm artifacts to .gitignore

2017-01-19 09:39 UTC, byshovets approved these changes

2017-01-19 10:14 UTC, merged