Contacts Tests and templates
Lv-219-Python/MoniNag pull request #43
Opened 2017-03-02 14:06 UTC by s0812

2017-03-02 18:07 UTC, lisovyk commented on moninag/templates/contact/verified.html
> +  <h3>You have confirmed email recieves from MoniNag!</h3>
Better to say 'email notification'

2017-03-04 11:13 UTC, ghost requested changes

2017-03-04 11:13 UTC, HenrikhB commented on moninag/tests/unittests/contact/test_views.py
> +        """Ensure that POST fails to create contact with invalid data on input and returns 400 status"""
line is too long

2017-03-04 11:13 UTC, HenrikhB commented on moninag/tests/unittests/contact/test_views.py
> +        """Ensure that POST fails to create contact with email which is already in use returns 400 status"""
line is too long

2017-03-04 11:19 UTC, hutsulyk requested changes
Your coverage in 97% for view :upside_down_face:

One more thing in put method :bug: 
Can I update only name for contact?
Because now I will get an error. Put demand email in body, even if I don't want to update it.

In general it works, and email verification works! :+1: 

P.S. Rebase with dev :upside_down_face:

2017-03-04 11:19 UTC, hutsulyk commented on moninag/templates/contact/verified.html
> +  <p>Click <a href="http://127.0.0.1:8000">here</a> to visit home page of MoniNag.</p>
Use some variable against static `href`, 
because if someone has different local settings it won't work I think :upside_down_face:

2017-03-04 11:19 UTC, hutsulyk commented on moninag/tests/unittests/contact/test_views.py
>          expected_json_response['response'] = to_dict(contact)
Why don't yo use contact.to_dict()? :upside_down_face:

2017-03-04 11:19 UTC, hutsulyk commented on moninag/tests/unittests/contact/test_views.py
> +        self.assertEqual(contact.email, 'test@test.test')
Post return json, why don't you check it? :upside_down_face:

2017-03-04 11:19 UTC, hutsulyk commented on moninag/contact/views.py
> +        except ValidationError:
Add except type in the rest part of this file where it is missing :slightly_smiling_face:

2017-03-04 11:19 UTC, hutsulyk commented on moninag/tests/unittests/contact/test_views.py
> +        self.assertIn(b'Incorrect JSON format', response._container[0])
Why don't you use JSONEqual? :space_invader:

2017-03-04 11:19 UTC, hutsulyk commented on moninag/tests/unittests/contact/test_views.py
> +        self.assertIn(b'User with such email already exists', response._container[0])
Again, why don't you use JSONEqual? :eagle:

2017-03-04 11:19 UTC, hutsulyk commented on moninag/tests/unittests/contact/test_views.py
> +        self.assertIn(b'Invalid email format', response._container[0])
Again, JSONEqual? :eagle:

2017-03-05 20:23 UTC, s0812 commented on moninag/templates/contact/verified.html
> +  <p>Click <a href="http://127.0.0.1:8000">here</a> to visit home page of MoniNag.</p>
@mhumetskyi replaced with '/'. It should work for any local settings.

2017-03-05 20:24 UTC, s0812 commented on moninag/templates/contact/verified.html
> +  <h3>You have confirmed email recieves from MoniNag!</h3>
@lisovyk replaced with 'email notification' ^_^

2017-03-05 20:26 UTC, s0812 commented on moninag/templates/contact/verified.html
> +  <p>Click <a href="http://127.0.0.1:8000">here</a> to visit home page of MoniNag.</p>
@mhumetskyi coverage now is 100%. And u can update only one field of contact. In my case it works.

2017-03-07 13:06 UTC, lisovyk commented on moninag/tests/unittests/contact/test_views.py
> +                           'secon_name': 'newSecondName'})
You wanted to write `second_name` ?

2017-03-07 13:23 UTC, mhumetskyi commented on moninag/contact/views.py
> +        else:
Code duplication :upside_down_face: 

Rewrite for example this way:
```
if 'email' in contact_params:
    email = contact_params.get('email')
    try:
        validate_email(email)
    except ValidationError:
        json_response['error'] = 'Invalid email format.'
        return JsonResponse(json_response, status=400)

 contact = Contact.get_by_id(contact_id)
 if not contact:
    json_response['error'] = 'Contact was not found.'
    return JsonResponse(json_response, status=404)

if not request.user.id == contact.user.id:
    return HttpResponse(status=403)

contact.update(**contact_params)
json_response['response'] = contact.to_dict()
return JsonResponse(json_response, status=200)
```

2017-03-07 13:37 UTC, hutsulyk reviewed
Add method get_by_email in Contacts to use in view.
Simplify try blocks in post :slightly_smiling_face:

2017-03-07 19:17 UTC, s0812 commented on moninag/tests/unittests/contact/test_views.py
> +                           'secon_name': 'newSecondName'})
@lisovyk everything is fine. In this way i tested an invalid field.

2017-03-07 22:56 UTC, mhumetskyi commented on moninag/tests/unittests/contact/test_views.py
> +                           'secon_name': 'newSecondName'})
@s0812 It would be cleaner if name it  `invalid_field`, but it is optional :slightly_smiling_face:

2017-03-09 09:47 UTC, s0812 commented
@mhumetskyi seems that everything is fine.

2017-03-09 10:04 UTC, mhumetskyi commented on .gitignore
> +
Why do you add these files? :slightly_smiling_face:

2017-03-09 10:09 UTC, s0812 commented on .gitignore
> +
Whops, my fault.

2017-03-09 10:25 UTC, ghost approved these changes

2017-03-09 12:15 UTC, lhalam requested changes
:(

2017-03-09 12:15 UTC, lhalam commented on moninag/contact/models.py
>          :return: QuerySet<Contact>: QuerySet of contact.
Method get do not return QuerySets¶

2017-03-09 12:15 UTC, lhalam commented on moninag/contact/models.py
>              Contact.objects.get(id=contact_id)
bad construct, not logical
for example:
```
contact  = Contact.objects.get(id=contact_id)
return contact
```

2017-03-09 12:15 UTC, lhalam commented on moninag/contact/models.py
>          return Contact.objects.filter(user=user_id)
use method **get()**, because this method must return one object, rather than a  QuerySet

2017-03-09 12:15 UTC, lhalam commented on moninag/contact/models.py
> +        return Contact.objects.filter(email=email)
use method **get()**, because this method must return one object, rather than a  QuerySet

2017-03-09 12:15 UTC, lhalam commented on moninag/contact/views.py
>                      error: <error message>
`line 35` `response: <list of contacts> or <contact>`

2017-03-09 12:15 UTC, lhalam commented on moninag/contact/views.py
> +            if Contact.get_by_email(email):
If another user has added a contact with this e-mail?

2017-03-09 12:15 UTC, lhalam commented on moninag/contact/views.py
>          try:
bad practice use `try` in View

2017-03-09 12:15 UTC, lhalam commented on moninag/contact/views.py
> +        if 'email' in contact_params:
The wrong condition, given the previous line, and  did not understand the need for the next line

2017-03-09 12:15 UTC, lhalam commented on moninag/contact/views.py
> +            try:
Again the same "try", maybe makes sense to create the function for validating.

2017-03-22 13:43 UTC, lhalam approved these changes

2017-03-22 19:59 UTC, hutsulyk approved these changes

2017-03-22 20:22 UTC, merged