Added tests for registration view
Lv-219-Python/MoniNag pull request #46
Opened 2017-03-03 12:58 UTC by lisovyk

Coverage - 100%

2017-03-04 10:27 UTC, hutsulyk requested changes
Keep same style with quotes.
Replace double with single, where it is possible :paintbrush:

2017-03-04 10:27 UTC, hutsulyk commented on moninag/tests/unittests/registration/test_view.py
> +                                    'success': True})
Too long message lines `113 > 99`

Split them more :space_invader: 
```
expected_json = json.dumps({'error': {},
                            'message':
                                'Thank you for your time. '
                                'The confirmation code has been sent to your email. '
                                'In order to confirm the registration, '
                                'simply click on the link given in it.',
                            'success': True})
```

2017-03-04 10:27 UTC, hutsulyk commented on moninag/tests/unittests/registration/test_view.py
> +        """First, we register a user"""
Maybe it is better to use `#` for inline comments. 
And add blank line after docstring.

2017-03-04 10:27 UTC, hutsulyk commented on moninag/tests/unittests/registration/test_view.py
> +        """Now we try to register that email once more"""
`#` :upside_down_face:

2017-03-04 10:27 UTC, hutsulyk commented on moninag/tests/unittests/registration/test_view.py
> +        expected_json = json.dumps({'error': 'This email is already registered. Please try another',
Too long line :loop:

2017-03-04 10:27 UTC, hutsulyk commented on moninag/tests/unittests/registration/test_view.py
> +        expected_json = json.dumps({'error': "The email address you've entered has not a valid format",
Too long line :loop:

2017-03-04 10:27 UTC, hutsulyk commented on moninag/tests/unittests/registration/test_view.py
> +                                    'message': 'An email has been sent to testmail@test.so. Please check its inbox to continue reseting password.',
Too long line :loop:

2017-03-04 10:27 UTC, hutsulyk commented on moninag/tests/unittests/registration/test_view.py
> +        expected_json = json.dumps({'error': "The email address you've entered has not a valid format",
Too long line :loop:

2017-03-04 10:27 UTC, hutsulyk commented on moninag/tests/unittests/registration/test_view.py
> +                     'message': "Password has been reset. In 5 seconds you will be redirected to the login page.",
Too long line :loop:

2017-03-04 10:27 UTC, hutsulyk commented on moninag/tests/unittests/registration/test_view.py
> +    @mock.patch('registration.views.urlsafe_base64_decode', Fakeuidb64.uidb64)
`urlsafe_base64_decode` is a function, you don't need to use class, function alone  will work :octopus:

2017-03-04 10:27 UTC, hutsulyk commented on moninag/tests/unittests/registration/test_view.py
> +        self.assertEqual(response.status_code, 200)
Why do you need register user to run this test?
You have one user already in setup :bust_in_silhouette:

2017-03-04 10:27 UTC, mhumetskyi commented on moninag/tests/unittests/registration/test_view.py
> +        user.save()
Again, why do you need register user to run this test? :upside_down_face:

2017-03-04 10:27 UTC, mhumetskyi commented on moninag/tests/unittests/registration/test_view.py
> +class LoginView(TestCase):
It is better to name class with `Test` word, for example `LoginViewTest` :space_invader:

2017-03-04 10:27 UTC, mhumetskyi commented on moninag/tests/unittests/registration/test_view.py
> +        return '15'
Why do you choose 15? :slightly_smiling_face: 
I ask, because it matters :upside_down_face:

2017-03-04 11:19 UTC, ghost requested changes
Use pylint

2017-03-04 11:19 UTC, HenrikhB commented on moninag/tests/unittests/registration/test_view.py
> +    def uidb64(self):
missing docstring

2017-03-04 13:03 UTC, lisovyk commented on moninag/tests/unittests/registration/test_view.py
> +    def uidb64(self):
The whole class is meant to mock the uidb64. What should I write there?

2017-03-04 13:06 UTC, lisovyk commented on moninag/tests/unittests/registration/test_view.py
> +        return '15'
uidb64 get's the user's ID in the view. Therefore i mock it to return 15, which is an id of tested user :upside_down_face:

2017-03-04 13:40 UTC, lisovyk commented on moninag/tests/unittests/registration/test_view.py
> +                                    'success': True})
isn't it 88, not 99? The code will be ugly if I make it to 88. I've managed to shorten it t 99 symbols though.

2017-03-04 13:53 UTC, mhumetskyi commented on moninag/tests/unittests/registration/test_view.py
> +        user.save()
User is not in danger, you can omit saving him :dagger: :upside_down_face:

2017-03-04 13:55 UTC, lisovyk commented on moninag/tests/unittests/registration/test_view.py
> +        user.save()
It is a leftover from a different user I already got rid of  :scissors:

2017-03-04 13:56 UTC, mhumetskyi commented on moninag/tests/unittests/registration/test_view.py
> +        user.save()
Do really need to get user at all? :slightly_smiling_face:

2017-03-04 13:58 UTC, lisovyk commented on moninag/tests/unittests/registration/test_view.py
> +        user.save()
The test will be so lonely without a user.. As you wish :sob:

2017-03-04 13:58 UTC, mhumetskyi commented on moninag/tests/unittests/registration/test_view.py
> +                                         'the link given in it.',
Indents missing one space :upside_down_face:

2017-03-04 13:59 UTC, mhumetskyi commented on moninag/tests/unittests/registration/test_view.py
> +        user = CustomUser.objects.get(id=1000)
Unused user :space_invader:

2017-03-04 14:16 UTC, mhumetskyi commented on moninag/tests/unittests/registration/test_view.py
> +    # Mock uidb64 for password reset
Use `"""` for doc strings :upside_down_face:

2017-03-04 14:16 UTC, mhumetskyi commented on moninag/tests/unittests/registration/test_view.py
> +    # Mock token for password reset
`"""` :slightly_smiling_face:

2017-03-04 14:26 UTC, hutsulyk approved these changes
Check pylint output, everything else is fine :slightly_smiling_face:

2017-03-07 12:43 UTC, ghost approved these changes

2017-03-07 12:43 UTC, merged