Add navigation tree view, add ui view
Lv-219-Python/MoniNag pull request #56
Opened 2017-03-12 09:50 UTC by zirka28

2017-03-12 11:11 UTC, mhumetskyi commented on moninag/moninag/urls.py
> +]
Endline

2017-03-12 11:19 UTC, mhumetskyi commented on moninag/static/src/ts/app/navs/side-nav/side-nav.component.ts
> +}
Endline :slightly_smiling_face:

2017-03-12 11:20 UTC, ghost requested changes

2017-03-12 11:20 UTC, HenrikhB commented on moninag/static/src/ts/app/navs/side-nav/side-nav.component.ts
> +}
endline?

2017-03-12 11:20 UTC, HenrikhB commented on moninag/utils/navigation_tree_view.py
> +from server.models import Server
group imports

2017-03-12 11:20 UTC, HenrikhB commented on moninag/utils/navigation_tree_view.py
> +from django.http import JsonResponse
module docstring

2017-03-12 11:20 UTC, HenrikhB commented on moninag/utils/navigation_tree_view.py
> +def get_navigation_tree(request):
method docstring

2017-03-12 11:20 UTC, mhumetskyi commented on moninag/static/src/ts/app/navs/side-nav/side-nav.service.ts
> +export class SideNavService {
Delete empty line between class and `@Injectable()` :upside_down_face:

2017-03-12 11:24 UTC, hutsulyk reviewed
Interesting that in Firefox menu doesn't work. Firefox doesn't know `$event`. In Chrome it works :upside_down_face: 

Great job! Fix comments only :slightly_smiling_face:

2017-03-12 13:06 UTC, zirka28 commented on moninag/static/src/ts/app/navs/side-nav/side-nav.component.ts
> +}
done

2017-03-12 13:06 UTC, zirka28 commented on moninag/static/src/ts/app/navs/side-nav/side-nav.component.ts
> +}
done

2017-03-12 13:06 UTC, zirka28 commented on moninag/utils/navigation_tree_view.py
> +from django.http import JsonResponse
done

2017-03-12 13:36 UTC, hutsulyk approved these changes

2017-03-13 13:04 UTC, ghost approved these changes
awesome work! :+1:

2017-03-13 13:35 UTC, merged